### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by WaielonH** [UBC-MDS/cervical-cancer-predictor#11]
@revathyponn 
@morrismanfung 

Reply to this issue with all the packages that have been used with your scripts so that I can create the environment file and update the README

**Comment by morrismanfung** [comment]
I used scikit-learn, joblib, altair.

**Comment by samson-bakos** [comment]
no Pandas Morris?

**Comment by morrismanfung** [comment]
> no Pandas Morris?

Oh right also numpy and pandas :)

and docopt-ng! https://github.com/jazzband/docopt-ng

**Comment by morrismanfung** [comment]
As I will use the method suggested by Joel to save the figures (https://ubc-mds.slack.com/archives/C24GEK199/p1669269033666769), I will also need vl-convert-python to be installed in the environment.
