### ISSUE TITLE
Week 3 task - make file

### ISSUE THREAD

**Issue by revathyponn** [UBC-MDS/cervical-cancer-predictor#36]
While creating make file I have noticed that when we run the .py scripts they are creating the output folders outside our repository. We will have to update the output folder path in all the .py files. I will be updating all the .py files tomorrow by creating the make file branch. Please let me know if you are going to make any changes in .py files in the meantime.

**Comment by morrismanfung** [comment]
I changed `model_training.py` by breaking down the `main` function into multiple smaller functions.
