### ISSUE TITLE
Milestone 3 - Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/cervical-cancer-predictor#54]
Congratulations on finishing milestone 3! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Target all could be simplified by writing something like all: <report_target>. - 2 mechanics

**Comment:** You can only use the final report html for the ‘all’ section. 

- [ ] All contributions are expected to go through code review via a pull-request. -4 mechanics

**Comment:** It is not a good practice to have commits directly to the main branch (except for the merges), which is the required workflow for this course.

**Overall Comment:** The project is well-documented. The file/folder structure is easy to understand and the usage section is clear. I suggest that you add code cells so that commands can be copied easily. Also, for some of the scripts, the "Usage" was added in a new line which gave an error initially. It should be `Usage: script.py ......`.  
Well done and good luck with milestone 4!

**Comment by samson-bakos** [comment]
Hi @danielramandi , regarding the commits to main, we were taught in 521 that in a collaborative situation, it is fine to make commits to main when they are minor changes (i.e. to binary files) that we are certain will not break anything. It was even a quiz question.

While I understand the workflow for this project was to use branches, we did that for all relevant components of the data pipeline, and I feel we modelled good collaborative development practice in general. It seems unrealistic to have us branch and merge for correction of typos/ reformatting on the ReadMe, especially with branch protections in place. We had specific people in charge of maintaining/ updating different files, so there was no chance of any merge conflict/ workflow issues. 

-4 seems a little harsh when we clearly did understand the requisite workflow, and worked in an efficient/ realistic manner.
